// Package natsconf renders an Asty NATSConfig + node identity + peer
// list into a nats-server configuration file.
//
// The result is the single source of truth for what nats-server runs
// with: the agent writes it to disk before exec'ing nats-server, and
// the `asty -mode nats-conf` subcommand prints it to stdout for
// inspection.
package natsconf

import (
	"fmt"
	"sort"
	"strings"

	"asty/asty/internal/core/config"
)

// Input is everything Render needs beyond NATSConfig: per-node identity
// (server_name, bind addresses) and the list of peer IPs that populate
// cluster.routes. Peers are IPs of OTHER nodes; the local node is never
// in its own routes list.
//
// KeepClusterBlock forces the cluster{} block into the output even when
// Peers is empty. Set true ONLY for SIGHUP reloads of an already-
// clustered process — NATS rejects an empty-routes cluster{} on cold
// start (see the comment near the emit site).
type Input struct {
	Config           config.NATSConfig
	NodeID           string
	NodeIP           string
	Peers            []string
	KeepClusterBlock bool
}

// Render builds the nats-server configuration as a single string.
func Render(in Input) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# generated by asty — do not edit by hand\n")
	fmt.Fprintf(&b, "server_name: %q\n", in.NodeID)
	fmt.Fprintf(&b, "listen: %s:%d\n", in.NodeIP, in.Config.Server.Port)

	if js := in.Config.Server.JetStream; js.StoreDir != "" {
		b.WriteString("\njetstream {\n")
		fmt.Fprintf(&b, "  store_dir: %q\n", js.StoreDir)
		if js.MaxMemory != "" {
			fmt.Fprintf(&b, "  max_mem: %s\n", js.MaxMemory)
		}
		if js.MaxFile != "" {
			fmt.Fprintf(&b, "  max_file: %s\n", js.MaxFile)
		}
		b.WriteString("}\n")
	}

	// Emit cluster{} when we have peers OR the caller pinned it on for
	// a SIGHUP reload. NATS rejects an empty-routes cluster{} on cold
	// start ("requires configured routes or solicited leafnode"); on
	// reload it accepts it, which keeps a shrinking cluster in
	// clustered mode instead of flipping to standalone (the flip
	// otherwise leaves previously-replicated streams unreachable).
	if cl := in.Config.Server.Cluster; cl.Port > 0 && (len(in.Peers) > 0 || in.KeepClusterBlock) {
		b.WriteString("\ncluster {\n")
		if cl.Name != "" {
			fmt.Fprintf(&b, "  name: %q\n", cl.Name)
		}
		fmt.Fprintf(&b, "  listen: %s:%d\n", in.NodeIP, cl.Port)
		b.WriteString("  routes: [\n")
		for _, p := range in.Peers {
			fmt.Fprintf(&b, "    \"nats-route://%s:%d\"\n", p, cl.Port)
		}
		b.WriteString("  ]\n")
		b.WriteString("}\n")
	}

	if len(in.Config.Server.Accounts) > 0 {
		b.WriteString("\naccounts: {\n")
		// Sort account names so two renders of the same config produce
		// byte-identical output — important for change detection.
		names := make([]string, 0, len(in.Config.Server.Accounts))
		for name := range in.Config.Server.Accounts {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			writeAccount(&b, name, in.Config.Server.Accounts[name])
		}
		b.WriteString("}\n")
	}

	if sa := in.Config.Server.SystemAccount; sa != "" {
		fmt.Fprintf(&b, "\nsystem_account: %s\n", sa)
	}

	return b.String()
}

// writeAccount renders one account block. JetStream:true emits
// `jetstream: enabled` so the account can host streams and KV buckets.
func writeAccount(b *strings.Builder, name string, acc config.NATSAccount) {
	fmt.Fprintf(b, "  %s: {\n", name)
	if acc.JetStream {
		b.WriteString("    jetstream: enabled\n")
	}
	b.WriteString("    users: [\n")
	for _, u := range acc.Users {
		writeUser(b, u)
	}
	b.WriteString("    ]\n  }\n")
}

// writeUser renders one user. When Permissions is set, the user is
// restricted to the listed publish/subscribe subjects — used to lock
// the observer user down to STATSZ/JSZ request-reply only.
func writeUser(b *strings.Builder, u config.NATSUser) {
	if u.Permissions == nil {
		fmt.Fprintf(b, "      { user: %q, password: %q }\n", u.User, u.Password)
		return
	}
	fmt.Fprintf(b, "      { user: %q, password: %q, permissions: {\n", u.User, u.Password)
	fmt.Fprintf(b, "        publish:   { allow: [%s] }\n", quoteList(u.Permissions.Publish.Allow))
	fmt.Fprintf(b, "        subscribe: { allow: [%s] }\n", quoteList(u.Permissions.Subscribe.Allow))
	b.WriteString("      } }\n")
}

// quoteList formats a slice of subjects as a comma-separated, quoted
// list suitable for inlining inside a NATS allow/deny array.
func quoteList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(parts, ", ")
}
